# Generated by Django 5.1.1 on 2024-11-24 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalistaAdmision',
            fields=[
                ('cod_analista_adm', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre_ad', models.CharField(max_length=100)),
                ('correo_electronico_ad', models.EmailField(max_length=100)),
                ('telefono_ad', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=150)),
                ('num_aceptados', models.IntegerField(default=0)),
                ('num_rechazados', models.IntegerField(default=0)),
                ('num_pendientes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Analista_adm',
            },
        ),
        migrations.CreateModel(
            name='AnalistaCredito',
            fields=[
                ('cod_analista_ac', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre_ac', models.CharField(max_length=100)),
                ('correo_electronico_ac', models.EmailField(max_length=100)),
                ('telefono_ac', models.CharField(max_length=15)),
                ('direccion_ac', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Analista_credito',
            },
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('cod_solicitante', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre_sol', models.CharField(max_length=100)),
                ('ruc_sol', models.CharField(max_length=11)),
                ('dni_sol', models.CharField(max_length=8)),
                ('ubicacion_sol', models.CharField(max_length=150)),
                ('correo_electronico_sol', models.EmailField(max_length=100)),
                ('telefono_sol', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Solicitante',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('cod_solicitud', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('fecha_inicio_solicitud', models.DateField()),
                ('fecha_fin_solicitud', models.DateField(blank=True, null=True)),
                ('fecha_notificacion', models.DateField(blank=True, null=True)),
                ('estado_solicitud', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=50)),
                ('tipo_solicitud', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Renovación', 'Renovación')], max_length=50)),
                ('cod_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.solicitante')),
            ],
            options={
                'db_table': 'Solicitud',
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('cod_seguimiento', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('fecha_seguimiento', models.DateField()),
                ('indicadores', models.JSONField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('solicitud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='app.solicitud')),
            ],
            options={
                'db_table': 'Seguimiento',
            },
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('cod_entrevista', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('fecha_entrevista', models.DateField()),
                ('hora_inicio_entrevista', models.TimeField()),
                ('hora_fin_entrevista', models.TimeField()),
                ('resultados_entrevista', models.CharField(max_length=255)),
                ('observaciones_entrevista', models.TextField(blank=True, null=True)),
                ('solicitud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrevistas', to='app.solicitud')),
            ],
            options={
                'db_table': 'Entrevista',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('cod_documento', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre_doc', models.CharField(max_length=100)),
                ('tipo_doc', models.CharField(max_length=50)),
                ('ruta_doc', models.CharField(max_length=255)),
                ('fecha_recibido', models.DateField()),
                ('version', models.IntegerField()),
                ('estado_validacion', models.CharField(choices=[('VALIDADO', 'Validado'), ('RECHAZADO', 'Rechazado'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=20)),
                ('cod_analista_ac', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='app.analistacredito')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='app.solicitud')),
            ],
            options={
                'db_table': 'Documento_adm',
            },
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('cod_capacitacion', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('fecha_capacitacion', models.DateField()),
                ('temas_tratados', models.TextField()),
                ('asistencia', models.IntegerField()),
                ('solicitud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capacitaciones', to='app.solicitud')),
            ],
            options={
                'db_table': 'Capacitacion',
            },
        ),
        migrations.CreateModel(
            name='SolicitudAnalistaAdmision',
            fields=[
                ('cod_sol_analista_adm', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('analista_adm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='app.analistaadmision')),
                ('solicitud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analistas_admision', to='app.solicitud')),
            ],
            options={
                'db_table': 'Solicitud_Analista_adm',
            },
        ),
    ]
