-- DROP TABLE -> Modulo de equipos y recargas
DROP TABLE IF EXISTS Pedido_Equipo;
DROP TABLE IF EXISTS Factura;
DROP TABLE IF EXISTS SAP;
DROP TABLE IF EXISTS SUNAT;
DROP TABLE IF EXISTS Recarga;
DROP TABLE IF EXISTS Pedido;
DROP TABLE IF EXISTS Equipo;
DROP TABLE IF EXISTS Cliente;

-- CREATE TABLE -> Modulo de equipos y recargas

-- Tabla Cliente
CREATE TABLE Cliente (
    COD_CLIENTE VARCHAR(7) PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    RAZON_SOCIAL VARCHAR(150),
    TELEFONO VARCHAR(15),
    CORREO_EMPRESA VARCHAR(100),
    DIRECCION_CLIENTE VARCHAR(150),
    CREDITO_MAXIMO DECIMAL(10, 2),
    ESTADO_CLIENTE VARCHAR(50),
    FECHA_REGISTRO DATE,
    LINEA_CREDITO DECIMAL(10, 2),
    CLASE_PERSONA VARCHAR(50),
    REGION VARCHAR(50),
    REP_LEGAL VARCHAR(100)
);

-- Tabla Equipo
CREATE TABLE Equipo (
    COD_EQUIPO VARCHAR(9) PRIMARY KEY,
    NOMBRE_EQUIPO VARCHAR(100) NOT NULL,
    MARCA VARCHAR(50),
    MODELO VARCHAR(50),
    CATEGORIA VARCHAR(50),
    PRECIO_UNITARIO DECIMAL(10, 2),
    CANTIDAD_STOCK INT
);

-- Tabla Pedido
CREATE TABLE Pedido (
    COD_PEDIDO VARCHAR(9) PRIMARY KEY,
    FECHA_PEDIDO DATE NOT NULL,
    CANTIDAD_TOTAL INT,
    ESTADO_PEDIDO VARCHAR(50),
    FECHA_ENTREGA DATE,
    METODO_PAGO VARCHAR(50),
    OBSERVACIONES VARCHAR(255),
    DEMORA_PEDIDO INT,
    COD_CLIENTE VARCHAR(7),
    COD_RECARGA VARCHAR(9),
    FOREIGN KEY (COD_CLIENTE) REFERENCES Cliente(COD_CLIENTE),
    FOREIGN KEY (COD_RECARGA) REFERENCES Recarga(COD_RECARGA)
);

-- Tabla Pedido_Equipo
CREATE TABLE Pedido_Equipo (
    COD_PEDIDO_EQUIPO VARCHAR(9) PRIMARY KEY,
    COD_PEDIDO VARCHAR(9),
    COD_EQUIPO VARCHAR(9),
    CANTIDAD_PEDIDA INT,
    FOREIGN KEY (COD_PEDIDO) REFERENCES Pedido(COD_PEDIDO),
    FOREIGN KEY (COD_EQUIPO) REFERENCES Equipo(COD_EQUIPO)
);

-- Tabla Recarga
CREATE TABLE Recarga (
    COD_RECARGA VARCHAR(9) PRIMARY KEY,
    FECHA_SOLICITUD_RECARGA DATE NOT NULL,
    MONTO_RECARGA DECIMAL(10, 2),
    ESTADO_RECARGA VARCHAR(50),
    FECHA_LIBERACION_RECARGA DATE
);

-- Tabla SAP
CREATE TABLE SAP (
    COD_SAP VARCHAR(10) PRIMARY KEY,
    FECHA_VALIDACION DATE NOT NULL,
    ESTADO_VALIDACION VARCHAR(50),
    OBSERVACION_VALIDACION VARCHAR(255),
    LIMITE_CREDITO DECIMAL(10, 2),
    NUM_REFERENCIA_SAP_SUNAT VARCHAR(50),
    COD_PEDIDO VARCHAR(9),
    FOREIGN KEY (COD_PEDIDO) REFERENCES Pedido(COD_PEDIDO)
);

-- Tabla Factura
CREATE TABLE Factura (
    COD_FACTURA VARCHAR(10) PRIMARY KEY,
    MONTO_FACTURA DECIMAL(10, 2),
    FECHA_FACTURA DATE NOT NULL,
    ESTADO_FACTURA VARCHAR(50),
    NUM_REFERENCIA_SUNAT VARCHAR(50),
    COD_SAP VARCHAR(10),
    FOREIGN KEY (COD_SAP) REFERENCES SAP(COD_SAP)
);

-- Tabla SUNAT
CREATE TABLE SUNAT (
    COD_SUNAT VARCHAR(10) PRIMARY KEY,
    FECHA_ASIGNACION DATE NOT NULL,
    MONTO_SUNAT DECIMAL(10, 2),
    NUM_REFERENCIA_SUNAT VARCHAR(50),
    COD_SAP VARCHAR(10),
    FOREIGN KEY (COD_SAP) REFERENCES SAP(COD_SAP)
);


-------------------------------------------- CREACION DE TABLAS PARA EL DW
CREATE TABLE Dim_Analista (
    COD_ANALISTA_COBRANZAS VARCHAR(10) PRIMARY KEY,
    NOMBRE_ANALISTA_COBRANZA VARCHAR(100),
    REGION_ANALISTA_COBRANZA VARCHAR(100)
);
select * from Dim_Analista

CREATE TABLE Dim_Cliente (
    COD_CLIENTE VARCHAR(10) PRIMARY KEY,
    CREDITO_MAXIMO DECIMAL(10, 2),
    ESTADO_CLIENTE VARCHAR(50),
    LINEA_CREDITO DECIMAL(10, 2),
    REGION VARCHAR(50)
);

CREATE TABLE Dim_Deuda (
    COD_DEUDA VARCHAR(10) PRIMARY KEY,
    ESTADO_DEUDA VARCHAR(50),
    MONTO_DEUDA DECIMAL(10, 2),
    DIAS_RETRASO INT,
    ESTADO_COBRANZA VARCHAR(50),
    FECHA_VENCIMIENTO DATE
);

CREATE TABLE Dim_Tiempo (
    COD_TIEMPO SERIAL PRIMARY KEY, 
    FECHA DATE NOT NULL,
    YEAR INT,
    MONTH INT,
    DAY_MONTH INT,
    WEEK_YEAR INT,
    DAY_WEEK INT
);


CREATE TABLE Fact_Rep_Deuda (
    COD_REP_DEUDA SERIAL PRIMARY KEY,
    FECHA_REPORTE DATE NOT NULL,
    COD_ANALISTA_COBRANZA VARCHAR(10),
    COD_TIEMPO INT,
    COD_CLIENTE VARCHAR(10),
    COD_DEUDA VARCHAR(10),
    FOREIGN KEY (COD_ANALISTA_COBRANZA) REFERENCES Dim_Analista(COD_ANALISTA_COBRANZAS),
    FOREIGN KEY (COD_TIEMPO) REFERENCES Dim_Tiempo(COD_TIEMPO),
    FOREIGN KEY (COD_CLIENTE) REFERENCES Dim_Cliente(COD_CLIENTE),
    FOREIGN KEY (COD_DEUDA) REFERENCES Dim_Deuda(COD_DEUDA)
);
DROP TABLE Fact_Rep_Deuda


-- INSERTS ETL DESDE EL MODULO DE COBRANZA
INSERT INTO Dim_Analista (COD_ANALISTA_COBRANZAS, NOMBRE_ANALISTA_COBRANZA, REGION_ANALISTA_COBRANZA)
SELECT COD_ANALISTA_COBRANZAS, NOMBRE_ANALISTA_COBRANZA, REGION_ANALISTA_COBRANZA
FROM Analista_cobranza;


INSERT INTO Dim_Cliente (COD_CLIENTE, CREDITO_MAXIMO, ESTADO_CLIENTE, LINEA_CREDITO, REGION)
SELECT COD_CLIENTE, CREDITO_MAXIMO, ESTADO_CLIENTE, LINEA_CREDITO, REGION
FROM Cliente;


INSERT INTO Dim_Deuda (COD_DEUDA, ESTADO_DEUDA, MONTO_DEUDA, DIAS_RETRASO, ESTADO_COBRANZA, FECHA_VENCIMIENTO)
SELECT COD_DEUDA, ESTADO_DEUDA, MONTO_DEUDA, DIAS_RETRASO, ESTADO_COBRANZA, FECHA_VENCIMIENTO
FROM Deuda;


INSERT INTO Dim_Tiempo (FECHA, YEAR, MONTH, DAY_MONTH, WEEK_YEAR, DAY_WEEK)
SELECT 
    FECHA_VENCIMIENTO, 
    EXTRACT(YEAR FROM FECHA_VENCIMIENTO), 
    EXTRACT(MONTH FROM FECHA_VENCIMIENTO), 
    EXTRACT(DAY FROM FECHA_VENCIMIENTO),
    EXTRACT(WEEK FROM FECHA_VENCIMIENTO), 
    EXTRACT(DOW FROM FECHA_VENCIMIENTO)
FROM Deuda;


INSERT INTO Fact_Rep_Deuda (FECHA_REPORTE, COD_ANALISTA_COBRANZA, COD_TIEMPO, COD_CLIENTE, COD_DEUDA)
SELECT 
    CURRENT_DATE,
    D.COD_ANALISTA_COBRANZA, 
    T.COD_TIEMPO, 
    C.COD_CLIENTE, 
    D.COD_DEUDA
FROM 
    Deuda D
JOIN Cliente C ON D.COD_CLIENTE = C.COD_CLIENTE
JOIN Dim_Tiempo T ON D.FECHA_VENCIMIENTO = T.FECHA;

-----------------------------------------------------
