# Generated by Django 5.1.3 on 2024-11-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalistaCobranza',
            fields=[
                ('cod_analista_cobranzas', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre_analista_cobranza', models.CharField(max_length=100)),
                ('fecha_de_contratacion_cobranza', models.DateField()),
                ('telefono_analista_cobranza', models.CharField(max_length=20)),
                ('correo_analista_cobranza', models.CharField(max_length=100)),
                ('region_analista_cobranza', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'analista_cobranza',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cod_cliente', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('razon_social', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo_empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_cliente', models.CharField(blank=True, max_length=150, null=True)),
                ('credito_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado_cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('linea_credito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('clase_persona', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('rep_legal', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('cod_deuda', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('estado_deuda', models.CharField(blank=True, max_length=50, null=True)),
                ('monto_deuda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dias_retraso', models.IntegerField(blank=True, null=True)),
                ('estado_cobranza', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'deuda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimAnalistaRp',
            fields=[
                ('ind_analista', models.CharField(blank=True, max_length=9, null=True)),
                ('nam_analista', models.CharField(blank=True, max_length=100, null=True)),
                ('reg_analista', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'dim_analista_rp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimCalendarioRp',
            fields=[
                ('ind_date', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cln', models.DateField(blank=True, null=True)),
                ('periodo_cln', models.IntegerField(blank=True, null=True)),
                ('year_cln', models.CharField(blank=True, max_length=4, null=True)),
                ('mes_cln', models.IntegerField(blank=True, null=True)),
                ('mes_nom_cln', models.CharField(blank=True, max_length=50, null=True)),
                ('dia_cln', models.IntegerField(blank=True, null=True)),
                ('trim_cln', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'dim_calendario_rp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimClienteRp',
            fields=[
                ('ind_cliente', models.CharField(blank=True, max_length=9, null=True)),
                ('nam_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('sta_cliente', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'dim_cliente_rp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactReporteDeudas',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ind_analista', models.CharField(blank=True, max_length=9, null=True)),
                ('reg_analista', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_cobranza', models.CharField(blank=True, max_length=50, null=True)),
                ('ind_date', models.IntegerField(blank=True, null=True)),
                ('ind_cliente', models.CharField(blank=True, max_length=9, null=True)),
                ('suma_monto_deuda_analista', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('suma_monto_deuda_region', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cantidad_clientes_atrasado_analista', models.BigIntegerField(blank=True, null=True)),
                ('cantidad_clientes_al_dia_analista', models.BigIntegerField(blank=True, null=True)),
                ('cantidad_clientes_cobranza_admin_trimestre', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fact_reporte_deudas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotificacionCobranza',
            fields=[
                ('cod_notificacion_cobranza', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('fecha_envio', models.DateField()),
                ('tipo_notificacion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'notificacion_cobranza',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
